# Generated by Django 5.2.4 on 2025-08-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hate_rate',
            field=models.FloatField(default=0.0, help_text='this show how hate speech is each comment'),
            preserve_default=False,
        ),
    ]
