# docker-compose.yml

version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"  # Map Docker port 5432 to local 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
