# Generated by Django 5.2.4 on 2025-07-08 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the discussion (e.g., group or chat title)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description or context for the discussion')),
                ('is_active', models.BooleanField(default=True, help_text='Can be used to archive or deactivate a discussion')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the discussion was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the discussion was updated')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the Topic was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the Topic was updated')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Discussion.discussion')),
            ],
        ),
    ]
