# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: share_news.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'share_news.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10share_news.proto\x12\x05share\"+\n\x19GetShareNewsByUserRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\"\x80\x01\n\x10ShareNewsMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cuserIdSender\x18\x02 \x01(\x05\x12\x0e\n\x06newsId\x18\x03 \x01(\x05\x12\x16\n\x0euserIdReceiver\x18\x04 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x11\n\tcreatedAt\x18\x06 \x01(\t\"D\n\x1aGetShareNewsByUserResponse\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.share.ShareNewsMessage\"d\n\x13\x41\x64\x64ShareNewsRequest\x12\x14\n\x0cuserIdSender\x18\x01 \x01(\x05\x12\x0e\n\x06newsId\x18\x02 \x01(\x05\x12\x16\n\x0euserIdReceiver\x18\x03 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"=\n\x14\x41\x64\x64ShareNewsResponse\x12%\n\x04item\x18\x01 \x01(\x0b\x32\x17.share.ShareNewsMessage\"-\n\x16RemoveShareNewsRequest\x12\x13\n\x0bshareNewsId\x18\x01 \x01(\x05\".\n\x17RemoveShareNewsResponse\x12\x13\n\x0bshareNewsId\x18\x01 \x01(\x05\x32\x88\x02\n\x10ShareNewsService\x12Y\n\x12GetShareNewsByUser\x12 .share.GetShareNewsByUserRequest\x1a!.share.GetShareNewsByUserResponse\x12G\n\x0c\x41\x64\x64ShareNews\x12\x1a.share.AddShareNewsRequest\x1a\x1b.share.AddShareNewsResponse\x12P\n\x0fRemoveShareNews\x12\x1d.share.RemoveShareNewsRequest\x1a\x1e.share.RemoveShareNewsResponseB\x17\xaa\x02\x14ShareNewsGrpc.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'share_news_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\024ShareNewsGrpc.Protos'
  _globals['_GETSHARENEWSBYUSERREQUEST']._serialized_start=27
  _globals['_GETSHARENEWSBYUSERREQUEST']._serialized_end=70
  _globals['_SHARENEWSMESSAGE']._serialized_start=73
  _globals['_SHARENEWSMESSAGE']._serialized_end=201
  _globals['_GETSHARENEWSBYUSERRESPONSE']._serialized_start=203
  _globals['_GETSHARENEWSBYUSERRESPONSE']._serialized_end=271
  _globals['_ADDSHARENEWSREQUEST']._serialized_start=273
  _globals['_ADDSHARENEWSREQUEST']._serialized_end=373
  _globals['_ADDSHARENEWSRESPONSE']._serialized_start=375
  _globals['_ADDSHARENEWSRESPONSE']._serialized_end=436
  _globals['_REMOVESHARENEWSREQUEST']._serialized_start=438
  _globals['_REMOVESHARENEWSREQUEST']._serialized_end=483
  _globals['_REMOVESHARENEWSRESPONSE']._serialized_start=485
  _globals['_REMOVESHARENEWSRESPONSE']._serialized_end=531
  _globals['_SHARENEWSSERVICE']._serialized_start=534
  _globals['_SHARENEWSSERVICE']._serialized_end=798
# @@protoc_insertion_point(module_scope)
