# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Page.grpc import share_news_pb2 as share__news__pb2


GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in share_news_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShareNewsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetShareNewsByUser = channel.unary_unary(
                '/share.ShareNewsService/GetShareNewsByUser',
                request_serializer=share__news__pb2.GetShareNewsByUserRequest.SerializeToString,
                response_deserializer=share__news__pb2.GetShareNewsByUserResponse.FromString,
                _registered_method=True)
        self.AddShareNews = channel.unary_unary(
                '/share.ShareNewsService/AddShareNews',
                request_serializer=share__news__pb2.AddShareNewsRequest.SerializeToString,
                response_deserializer=share__news__pb2.AddShareNewsResponse.FromString,
                _registered_method=True)
        self.RemoveShareNews = channel.unary_unary(
                '/share.ShareNewsService/RemoveShareNews',
                request_serializer=share__news__pb2.RemoveShareNewsRequest.SerializeToString,
                response_deserializer=share__news__pb2.RemoveShareNewsResponse.FromString,
                _registered_method=True)


class ShareNewsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetShareNewsByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddShareNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveShareNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShareNewsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetShareNewsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShareNewsByUser,
                    request_deserializer=share__news__pb2.GetShareNewsByUserRequest.FromString,
                    response_serializer=share__news__pb2.GetShareNewsByUserResponse.SerializeToString,
            ),
            'AddShareNews': grpc.unary_unary_rpc_method_handler(
                    servicer.AddShareNews,
                    request_deserializer=share__news__pb2.AddShareNewsRequest.FromString,
                    response_serializer=share__news__pb2.AddShareNewsResponse.SerializeToString,
            ),
            'RemoveShareNews': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveShareNews,
                    request_deserializer=share__news__pb2.RemoveShareNewsRequest.FromString,
                    response_serializer=share__news__pb2.RemoveShareNewsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'share.ShareNewsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('share.ShareNewsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShareNewsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetShareNewsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/share.ShareNewsService/GetShareNewsByUser',
            share__news__pb2.GetShareNewsByUserRequest.SerializeToString,
            share__news__pb2.GetShareNewsByUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddShareNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/share.ShareNewsService/AddShareNews',
            share__news__pb2.AddShareNewsRequest.SerializeToString,
            share__news__pb2.AddShareNewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveShareNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/share.ShareNewsService/RemoveShareNews',
            share__news__pb2.RemoveShareNewsRequest.SerializeToString,
            share__news__pb2.RemoveShareNewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
