# Generated by Django 5.2.4 on 2025-07-12 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name of the page.', max_length=100, unique=True)),
                ('post_count', models.IntegerField(default=0, help_text='The total number of posts on this page.')),
                ('follower_count', models.IntegerField(default=0, help_text='The total number of followers for this page.')),
                ('following_count', models.IntegerField(default=0, help_text='The total number of accounts this page is following.')),
                ('page_description', models.TextField(blank=True, help_text="A detailed description of the page's content or purpose.", max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the page was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the page was last updated.')),
                ('follows', models.ManyToManyField(blank=True, help_text='Other pages that this page is following.', related_name='followed_by', to='Page.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pages',
                'ordering': ['follower_count'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the news post.', max_length=255)),
                ('text', models.TextField(help_text='The full content of the news post.')),
                ('like_count', models.IntegerField(default=0, help_text='The number of likes this news post has received.')),
                ('comment_count', models.IntegerField(default=0, help_text='The number of comment this news post has received.')),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the news post was published.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the news post was last updated.')),
                ('likes', models.ManyToManyField(blank=True, help_text='Users who liked this news post.', related_name='liked_news', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(help_text='Each news post must be associated with one page.', on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='Page.page')),
            ],
            options={
                'verbose_name_plural': 'News Posts',
                'ordering': ['-published_date'],
            },
        ),
    ]
