# Generated by Django 5.2.4 on 2025-07-12 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Page', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='This is the content of the comment', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the comment was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the comment was last updated.')),
                ('news', models.ForeignKey(help_text='each comment has to have reference to specific post', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Page.news')),
                ('reply', models.ForeignKey(blank=True, help_text='Optional reference to a parent comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Comment.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
